from paralex import paralex_factory

freq_antiquitas = {"name": "frequency_Antiquitas",
                   "title": "Frequency in the Antiquitas",
                   "description": "The frequency of this item in the Antiquitas epoch "
                                  "in Tombeur's Thesaurus (from the origins to the end of the 2nd century A.D.)",
                   "type": "number"
                   }
freq_aetasPatrum = {"name": "frequency_AetasPatrum",
                    "title": "Frequency in the Aetas Patrum",
                    "description": "The frequency of this item in the Aetas Patrum epoch "
                                   "in Tombeur's Thesaurus (2nd century-735 A.D.)",
                    "type": "number"
                    }
freq_mediumAeuum = {"name": "frequency_MediumAeuum",
                    "title": "Frequency in the Medium Aeuum",
                    "description": "The frequency of this item in the Medium Aeuum epoch "
                                   "in Tombeur's Thesaurus (736-1499)",
                    "type": "number"
                    }
freq_recentiorLatinitas = {"name": "frequency_RecentiorLatinitas",
                  "title": "Frequency in the Recentior Latinitas",
                  "description": "The frequency of this item in the Recention Latinitas epoch "
                                 "in Tombeur's Thesaurus (1500-1965)",
                  "type": "number"
                  }

freq_cols = [freq_antiquitas, freq_aetasPatrum, freq_mediumAeuum, freq_recentiorLatinitas]

package = paralex_factory("LatInfLexi",
                          {
                              "forms": {"path": "LatInfLexi-forms.csv",
                                        "schema": {"fields": freq_cols}
                                        },
                              "cells": {"path": "LatInfLexi-cells.csv",
                                        "schema": {
                                            "fields": [{"name": "cell_romance_aligned",
                                                        "title": "cell code in OODRVM",
                                                        "description": "The code used for this cell in the Oxford Online Database of Romance Verb Morphology",
                                                        "type": "string"
                                                        },
                                                       {"name": "cell_LatInfLexi_v1",
                                                        "title": "cell code in LatInfLexi v1.1",
                                                        "description": "The code used for this cell in the previous release of LatInfLexi (v1.1)",
                                                        "type": "string"
                                                        }
                                                       ] + freq_cols
                                        }
                                        },
                              "features-values": {"path": "LatInfLexi-features-values.csv"},
                              "sounds": {"path": "LatInfLexi-sounds.csv",
                                "schema": {
                                  "fields": 
                                    [{'name': 'tier',
                                      'title': 'Tier to which the feature pertains',
                                      'description': 'Tier to which the feature pertains',
                                      'type': 'string'},
                                     {'name': 'value',
                                      'title': 'Value of the feature',
                                      'description': 'Value of the feature for non segmental tiers',
                                      'type': 'string'},
                                     {'name': 'consonantal',
                                      'title': 'Whether the sound displays the feature [consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'sonorant',
                                      'title': 'Whether the sound displays the feature [sonorant]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [sonorant]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'voice',
                                      'title': 'Whether the sound displays the feature [voice]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [voice]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'laryngeal',
                                      'title': 'Whether the sound displays the feature [laryngeal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [laryngeal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'spread_glottis',
                                      'title': 'Whether the sound displays the feature [spread_glottis]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [spread_glottis]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'continuant',
                                      'title': 'Whether the sound displays the feature [continuant]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [continuant]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'nasal',
                                      'title': 'Whether the sound displays the feature [nasal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [nasal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'lateral',
                                      'title': 'Whether the sound displays the feature [lateral]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [lateral]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'labial_consonantal',
                                      'title': 'Whether the sound displays the feature [labial_consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labial_consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'coronal',
                                      'title': 'Whether the sound displays the feature [coronal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [coronal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'dorsal_consonantal',
                                      'title': 'Whether the sound displays the feature [dorsal_consonantal]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [dorsal_consonantal]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'syllabic',
                                      'title': 'Whether the sound displays the feature [syllabic]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [syllabic]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'labial_vocalic',
                                      'title': 'Whether the sound displays the feature [labial_vocalic]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [labial_vocalic]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'dorsal_vocalic',
                                      'title': 'Whether the sound displays the feature [dorsal_vocalic]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [dorsal_vocalic]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'high',
                                      'title': 'Whether the sound displays the feature [high]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [high]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]},
                                     {'name': 'back',
                                      'title': 'Whether the sound displays the feature [back]',
                                      'description': 'Binary feature (1/0) indicating whether the segment displays the feature [back]',
                                      'type': 'boolean',
                                      'trueValues': ["1"],
                                      'falseValues': ["0"]}]
                                    }
                                  },
                              "graphemes": {"path": "LatInfLexi-graphemes.csv"},
                              "lexemes": {"path": "LatInfLexi-lexemes.csv",
                                          "schema": {"fields": freq_cols}
                                          }
                          },
                          citation="Pellegrini, M. & Passarotti, M. & Beniamine, S. (2023). LatInfLexi 2.0. Online.",
                          version="2.0",
                          keywords=["Latin", "verbs", "nouns", "paradigms", "cells"],
                          id="http://doi.org/10.5281/zenodo.10522692",
                          contributors=[{'title': 'Matteo Pellegrini', 'role': 'author'},
                                        {'title': 'Marco Passarotti', 'role': 'contributor'},
                                        {'title': 'Sacha Beniamine', 'role': 'contributor'}],
                          licenses=[{'name': 'CC BY-SA 4.0 DEED',
                                     'title': 'Creative Commons Attribution-ShareAlike 4.0 International',
                                     'path': 'https://creativecommons.org/licenses/by-sa/4.0/'}],
                          name="latinflexi"
                          )
package.to_json("LatInfLexi-package.json")
